services:
#  Для каждого пользователя сколько раз использовал команду

  bot:
    build: .
    container_name: go-tg-bot
    restart: always
    environment:
#      - "CHANNEL_ID=${CHANNEL_ID}"
#      - "SEARCH_QUERY=${SEARCH_QUERY}"
#      - "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
#      - "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}"
      - TZ=Europe/Moscow
